baseURL: "https://www.rehabrepsphysicaltherapy.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Rehab Reps"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Rehab Reps"
  description: "Our mission is to empower you by optimizing movement, restoring function, and promoting pain-free performance to freely participate in the activities you love."
  images:
    - "logo.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "2593 Mayport Rd, STE 105, Atlantic Beach, Florida, 32233"
    # - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
     - "rehabreps@outlook.com"
     - "904.717.2269"

  copyright: "© 2024 Rehab Reps All Rights Reserved"

menus:
  # main:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

  #   - name: "How we work"
  #     url: "/#"
  #     weight: 2

  #   - name: "Our team"
  #     url: "/#"
  #     weight: 3

  #   - name: "Pricing"
  #     url: "/#"
  #     weight: 4

  #   - name: "Blog"
  #     url: "/blog"
  #     weight: 5

  buttons:
    - name: "Book Appointment"
      url: "https://rehabreps.janeapp.com/"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
